### ISSUE TITLE
Conection Omeka-S for Dspace 7.2

### ISSUE THREAD

**Issue by DanGastardelli** [omeka-s-modules/DspaceConnector#76]
Hello!

Is connection supported with DSpace 7.2?
I'm trying to connect Omeka-s to DSpace 7.2, but every attempt I get timeout. From versions 6 to 7 of DSpace there are important changes in the functioning of api-rest. Has anyone ever managed to make a connection of this type?

**Comment by matthewjmckinley** [comment]
Hi there,

DSpace 7.x is pretty new and we haven't had an opportunity to test against the DspaceConnector yet. Looking at the new API documentation, it appears they've changed the base API endpoint path from 'rest' to 'api/core', but the links for actually accessing collections & items otherwise appear similar. I wonder if you change the Endpoint value in the initial DSpaceConnector settings from 'rest' to 'api/core', if that would be successful? 

Note that this wouldn't work for the 'Import Entire Repository' option--I need to adjust that code to make it more flexible for different endpoints.

Also, would you be willing to share your DSpace 7.2 endpoint, so that I can test locally and see what other changes might need to be made? Thanks!

**Comment by DanGastardelli** [comment]
Thanks for the feedback!

I tried to put this endpoint but it didn't work and it ends up giving 'time out' in the apache log. 

The DSpace I'm working on is from a client, I can't divulge it but for testing it's possible to use the DSpace demo itself 'https://api7.dspace.org/server/#/server/api'.

**Comment by matthewjmckinley** [comment]
Great, thanks for that. Digging in further, you're right that DSpace has made substantial changes to API functionality between 6.x and 7.x. Our current pagination approach is based on parameters that don't apply in the 7.x API, so the pages aren't properly incrementing and our while() loop is just kind of spinning endlessly, hence the timeout.

Thanks for bringing this to our attention! Reconfiguring the module to work with the post-7.x API certainly seems doable but I'll need to check with the rest of the Omeka team first, to see about a solution that is backwards-compatible for current users who might not have upgraded yet.

**Comment by matthewjmckinley** [comment]
Post-7.x compatibility added in latest version
